### ISSUE TITLE
Aiming crosshair always shown.

### ISSUE THREAD

**Issue by mghimaran** [TheOldRealms/TOW_Core_Old#17]
Unsure if this is a bug, but for some reason the aiming crosshair that Bows/Crossbows get is always shown, I think this is due to some issue with the rifles affecting all other weapons but it's just odd looking.

![image](https://user-images.githubusercontent.com/39462769/119269110-5063d180-bbf6-11eb-9ad2-5b0ebf280c34.png)

Crosshair with a sword, it also turns red when it thinks the player can't shoot.

**Comment by Z3rca** [comment]
Thanks, i am currently working on this bug. The Crosshair is currently set that way , because in the native game, the crosshair disappears after the first shot. That's not cool for the outrider gun

**Comment by Z3rca** [comment]
done
